### ISSUE TITLE
Error in spark2.1: can't read csv data to dataframe

### ISSUE THREAD

**Issue by chenliang613** [databricks/spark-csv#408]
The below error in sparkshell:
scala> val csvdf = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/Users/apple/DEMO/3Mtestdata.csv")
java.lang.NoSuchMethodError: com.univocity.parsers.csv.CsvParserSettings.setUnescapedQuoteHandling(Lcom/univocity/parsers/csv/UnescapedQuoteHandling;)V
  at org.apache.spark.sql.execution.datasources.csv.CsvReader.<init>(CSVParser.scala:47)
  at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat.inferSchema(CSVFileFormat.scala:61)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$7.apply(DataSource.scala:184)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$7.apply(DataSource.scala:184)
  at scala.Option.orElse(Option.scala:289)
  at org.apache.spark.sql.execution.datasources.DataSource.org$apache$spark$sql$execution$datasources$DataSource$$getOrInferFileFormatSchema(DataSource.scala:183)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:387)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:152)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:135)
  ... 50 elided

**Comment by falaki** [comment]
How are you loading the library? It seems you do not have the univocity parser Jar.

**Comment by chenliang613** [comment]
I used the below script, can you tell me how to correctly add the univocity parser jar?
1. Starts spark-shell:
./bin/spark-shell --master local --packages com.databricks:spark-csv_2.11:1.5.0 
import org.apache.spark.sql.SQLContext
2.Reads csv data to dataframe:
val sqlContext = new SQLContext(sc)
val csvdf = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/Users/apple/DEMO/3Mtestdata.csv")

scala> val csvdf = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/Users/apple/DEMO/3Mtestdata.csv")
java.lang.NoSuchMethodError: com.univocity.parsers.csv.CsvParserSettings.setUnescapedQuoteHandling(Lcom/univocity/parsers/csv/UnescapedQuoteHandling;)V
  at org.apache.spark.sql.execution.datasources.csv.CsvReader.<init>(CSVParser.scala:47)
  at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat.inferSchema(CSVFileFormat.scala:61)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$7.apply(DataSource.scala:184)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$7.apply(DataSource.scala:184)
  at scala.Option.orElse(Option.scala:289)
  at org.apache.spark.sql.execution.datasources.DataSource.org$apache$spark$sql$execution$datasources$DataSource$$getOrInferFileFormatSchema(DataSource.scala:183)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:387)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:152)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:135)
  ... 48 elided

**Comment by chenliang613** [comment]
Same script is working fine in Spark1.6 ,as below : 

AppledeMacBook-Pro:spark-1.6.1-bin-hadoop2.6 apple$ ./bin/spark-shell --master local --packages com.databricks:spark-csv_2.10:1.5.0
Ivy Default Cache set to: /Users/apple/.ivy2/cache
The jars for the packages stored in: /Users/apple/.ivy2/jars
:: loading settings :: url = jar:file:/Users/apple/Downloads/spark-1.6.1-bin-hadoop2.6/lib/spark-assembly-1.6.1-hadoop2.6.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.databricks#spark-csv_2.10 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
	confs: [default]
	found com.databricks#spark-csv_2.10;1.5.0 in central
	found org.apache.commons#commons-csv;1.1 in local-m2-cache
	found com.univocity#univocity-parsers;1.5.1 in local-m2-cache
downloading https://repo1.maven.org/maven2/com/databricks/spark-csv_2.10/1.5.0/spark-csv_2.10-1.5.0.jar ...
	[SUCCESSFUL ] com.databricks#spark-csv_2.10;1.5.0!spark-csv_2.10.jar (75ms)
:: resolution report :: resolve 748ms :: artifacts dl 80ms
	:: modules in use:
	com.databricks#spark-csv_2.10;1.5.0 from central in [default]
	com.univocity#univocity-parsers;1.5.1 from local-m2-cache in [default]
	org.apache.commons#commons-csv;1.1 from local-m2-cache in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   3   |   1   |   1   |   0   ||   3   |   1   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent
	confs: [default]
	1 artifacts copied, 2 already retrieved (161kB/8ms)
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 1.6.1
      /_/

Using Scala version 2.10.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_73)
Type in expressions to have them evaluated.
Type :help for more information.
Spark context available as sc.
SQL context available as sqlContext.

scala> val csvdf = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/Users/apple/DEMO/3Mtestdata.csv")
csvdf: org.apache.spark.sql.DataFrame = [name: string, gender: string, province: string, singler: boolean, age: int]

scala> csvdf.show()
+----------+------+--------+-------+---+
|      name|gender|province|singler|age|
+----------+------+--------+-------+---+
|     Mills|  Male|      NS|   true| 29|
|    Torres|Female|      NT|  false| 46|
|   Swanson|Female|      MB|  false| 27|
|    Chavez|  Male|      AB|   true| 23|
|     Lynch|Female|      NL|  false| 22|
|     Cohen|  Male|      NU|  false| 49|
|      West|  Male|      PE|   true| 31|
|   Swanson|  Male|      AB|   true| 29|
|     Watts|Female|      AB|  false| 30|
|     Hicks|  Male|      PE|   true| 48|
|      Lowe|  Male|      NB|   true| 20|
|    Jacobs|  Male|      PE|   true| 20|
|   Freeman|  Male|      ON|  false| 58|
|Fitzgerald|Female|      AB|  false| 64|
|    Thomas|  Male|      NB|  false| 56|
|     Gross|Female|      BC|  false| 64|
|      Webb|  Male|      MB|   true| 39|
|     Poole|  Male|      NT|   true| 21|
|    Thomas|Female|      NS|   true| 57|
|     Drake|Female|      MB|   true| 62|
+----------+------+--------+-------+---+
only showing top 20 rows

**Comment by MarsJiao** [comment]
Did u solved this problem ? I met the same error in spark 2.1 when I run spark.read.csv("")

**Comment by chenliang613** [comment]
@MarsJiao   not solve yet :(
