### ISSUE TITLE
inferSchema does not work with Spark 1.3.0

### ISSUE THREAD

**Issue by kgs** [databricks/spark-csv#128]
I am using Scala 2.10.5 with Spark 1.3.0 from CDH (spark-csv_2.10 version 1.2.0). When I try to use inferSchema=true I get following exception:

	Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/types/AtomicType
		at com.databricks.spark.csv.CsvRelation.inferSchema(CsvRelation.scala:155)
		at com.databricks.spark.csv.CsvRelation.<init>(CsvRelation.scala:70)
		at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:138)
		at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:40)
		at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:28)
		at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:290)
		at org.apache.spark.sql.SQLContext.load(SQLContext.scala:679)
		at pl.cenatorium.App$.main(App.scala:17)
		at pl.cenatorium.App.main(App.scala)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:606)
		at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:569)
		at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:166)
		at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:189)
		at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:110)
		at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
	Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.types.AtomicType
		at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
		at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
		... 18 more

As far I can deduce from this stacktrace it looks that class org/apache/spark/sql/types/AtomicType is only present in Spark 1.4.0

**Comment by dtpeacock** [comment]
Scala's type inference has chosen this type signature:

`public static org.apache.spark.sql.types.AtomicType tryParseInteger(java.lang.String)`

As you say AtomicType is only available in 1.4! It's an easy fix, I will do it later today. A very quick workaround is to compile it with 1.3.

**Comment by kgs** [comment]
Thanks, I'll wait for fix then :)

**Comment by dtpeacock** [comment]
Hmm I can't seem to get rid of that reference even when it is removed from the type signature. It looks like the classes may have changed enough to not be compatible.  @falaki any suggestions?

I have confirmed that compiling against 1.3.0 fixes this issue.

**Comment by HollyXuCS** [comment]
Hi dtpeacock, I met the same issue.  Wonder when will the fix be available? Thanks!

**Comment by JoshRosen** [comment]
I was able to reproduce this issue as part of #138, which adds 1.3.0 to our Travis build matrix. My build configuration actually compiles against 1.4.0 but tests against 1.3.0, so it was able to reproduce this exact stacktrace. I'm going to go ahead and fix this as part of that patch; hopefully this will be easy now that we have a way to automate these compatibility tests.

**Comment by JoshRosen** [comment]
Using `javap`, I figured out why fixing the type signature inference was not sufficient to fix this issue: it looks like Scala still generates a classfile with a constant pool that contains AtomicType even though none of the class's bytecode references that class. What I think might be happening is that some intermediate compiler phase is causing AtomicType to be placed into the pool, but later phases of compilation remove the code that implicitly caused this reference. I don't think that this can be worked around by adding type ascriptions or casts, so I think our only options may be to either compile against 1.3.0, introduce some weird code in `tryParseTimestamp` to trick the compiler, or rewrite this class in Java.

**Comment by JoshRosen** [comment]
By the way, this is an interesting enough `scalac` behavior that I'm planning to write up a longer post on it once I have some time.

**Comment by dtpeacock** [comment]
Indeed - this was exactly what I found too!

It looked like it was present to be present in the StackMapTable, and I tried to trick the compiler by trying various type signatures but wasn't able to. Interesting stuff!

https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.7.4

**Comment by JoshRosen** [comment]
Hmm, switching the default build to 1.3.0 seems to cause the opposite problem when running against 1.4.0+: we get a similar error for `NativeType`.

**Comment by dtpeacock** [comment]
I've narrowed it down a bit - it is something to do with how the exceptions are handled in scalac.

It seems swapping `(allCatch opt Timestamp.valueOf(field)).isDefined)` out for something else removes the references in the StackMapTable in the class file..

**Comment by JoshRosen** [comment]
I found another workaround: define a method that returns the `StringType` constant, then call that method inside of `tryParseTimestamp` instead of putting `StringType` there directly. This is sufficient to make the compatibility tests pass.

**Comment by zonca** [comment]
I still get the same error with `inferSchema = 'true'` in `pyspark`:

    java.lang.NoClassDefFoundError: org/apache/spark/sql/types/AtomicType

with spark 1.3.0 (Cloudera) and `com.databricks:spark-csv_2.10:1.2.0`

Is there a workaround? is an older version of spark-csv working with spark 1.3.0?

**Comment by JoshRosen** [comment]
Hey @zonca,

The fix that I implemented in #138 is not present in `spark-csv` 1.2.0. There aren't any published releases which contain my patch, but you should be able to compile `spark-csv` yourself to produce a version which includes my fix.

**Comment by zonca** [comment]
thanks @JoshRosen I would rather use an older version, however I tried down to `1.0.0` with the `--packages` option and I get the same error. Or is there a way to force the version in `sqlContext.load(source="com.databricks.spark.csv"...)`

**Comment by zonca** [comment]
@JoshRosen do you have any plan to release a new version of `spark-csv` anytime soon? I managed to build my own jar, but for teaching I would prefer to have a released version to make it easier on the students.

**Comment by JoshRosen** [comment]
Hi @zonca,

I think that @falaki is the right person to ask about publishing a new release, since he manages that process for this library.

**Comment by falaki** [comment]
@zonca yes we will publish a new release soon.

**Comment by zonca** [comment]
thanks @falaki , that is great news, I need for teaching to have it available by November 3rd, would it be feasible?

**Comment by falaki** [comment]
Unfortunately, I cannot publish it in that time frame. I will publish a release in fourth week of November.

**Comment by stephanecollot** [comment]
Could someone share his jar in the meantime?

**Comment by eedduuar** [comment]
Hi, I use ""com.databricks" % "spark-csv_2.10" % "1.0.0"" with 1.3.0  and it worked

**Comment by falaki** [comment]
version 1.3.0 was just published.

**Comment by alokmathur** [comment]
I am using com.databricks 1.3.0 . but i am still getting this error:java.lang.NoClassDefFoundError: org/apache/spark/sql/types/AtomicType .

**Comment by anoopkhetan** [comment]
Hi,
I was also getting the same error "java.lang.NoClassDefFoundError: org/apache/spark/sql/types/AtomicType". with jar spark-csv_2.10-1.2..0.jar.
When I tried with jar spark-csv_2.10-1.4.0.jar, my issue is resolved.
