### PR TITLE
Test against Spark 1.3.0 and 1.5.0-rc2 in Travis

### LINKED ISSUE #128: inferSchema does not work with Spark 1.3.0
I am using Scala 2.10.5 with Spark 1.3.0 from CDH (spark-csv_2.10 version 1.2.0). When I try to use inferSchema=true I get following exception:

	Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/types/AtomicType
		at com.databricks.spark.csv.CsvRelation.inferSchema(CsvRelation.scala:155)
		at com.databricks.spark.csv.CsvRelation.<init>(CsvRelation.scala:70)
		at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:138)
		at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:40)
		at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:28)
		at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:290)
		at org.apache.spark.sql.SQLContext.load(SQLContext.scala:679)
		at pl.cenatorium.App$.main(App.scala:17)
		at pl.cenatorium.App.main(App.scala)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:606)
		at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:569)
		at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:166)
		at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:189)
		at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:110)
		at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
	Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.types.AtomicType
		at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
		at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
		... 18 more

As far I can deduce from this stacktrace it looks that class org/apache/spark/sql/types/AtomicType is only present in Spark 1.4.0

### PR DESCRIPTION
**Pull request by JoshRosen**
This patch adds Spark 1.3.0 and 1.5.0-rc2 to our Travis build matrix. I removed the use of TestSQLContext since that class has been removed in Spark 1.5.

This patch also fixes #128, a binary incompatibility which broke schema inference on Spark 1.3.x.

### CODE REVIEW

File: build.sbt [hunk 1]
```diff
@@ -69,5 +71,5 @@ libraryDependencies += "com.novocode" % "junit-interface" % "0.9" % "test"
 
 ScoverageSbtPlugin.ScoverageKeys.coverageHighlighting := {
   if (scalaBinaryVersion.value == "2.10") false
-  else false
+  else true
```
Comment (JoshRosen) [inline build.sbt]: This was an obvious typo. Changing this should give us more precise coverage metrics from Codecov.

File: build.sbt [hunk 2]
```diff
@@ -59,7 +59,9 @@ pomExtra := (
 
 spName := "databricks/spark-csv"
 
-sparkVersion := "1.4.0"
+sparkVersion := sys.props.get("spark.version").getOrElse("1.4.0")
+
+resolvers += "Spark 1.5.0 RC1 Snapshot" at "https://repository.apache.org/content/repositories/orgapachespark-1137"
```
Comment (falaki) [inline build.sbt]: Please leave a TODO so we remember to update this once Spark 1.5 is released.

**Comment by falaki** [comment]
LGTM

**Comment by JoshRosen** [comment]
Looks like the 1.5.0 tests are failing due to some classloading issue:

```scala
19:43:32.007 ERROR org.apache.spark.executor.Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.io.IOException: java.lang.ClassNotFoundException: scala.Some
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1163)
	at org.apache.spark.Accumulable.readObject(Accumulators.scala:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.skipCustomData(ObjectInputStream.java:1956)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:72)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:98)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: scala.Some
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:67)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:500)
	at org.apache.spark.Accumulable$$anonfun$readObject$1.apply$mcV$sp(Accumulators.scala:152)
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1160)
	... 24 more
```

**Comment by JoshRosen** [comment]
I also have to alter the build matrix to not test 1.5 with Java 6.

**Comment by JoshRosen** [comment]
I just realized that this is sort of testing the wrong thing: we should be compiling with a fixed version of Spark and running tests with different versions in order to better simulate how our released library will actually be used. I'm going to update the Travis build to do this.

**Comment by JoshRosen** [comment]
The 1.3.0 build is failing due to #128, so I'll push a commit to fix that as part of this pull request.

**Comment by JoshRosen** [comment]
@falaki, this should now be ready for another round of review. Please pay careful attention to some of the build changes that I made in order to test support for Spark 1.3.0 as well (I fixed a bug in 1.3.x support).

**Comment by falaki** [comment]
Looks good to me. Thanks for tracking down the issue.
